//Only interface exports here
export * from './song';
export * from './generalSearch';
export * from './albumResult';
export * from './ArtistInAlbum';
export * from './albumInStats';
export * from './donationHistory';
export * from './dbError';
export * from './userOnDb';